### ISSUE TITLE
Asking for the patent race's script

### ISSUE THREAD

**Issue by nekotalabana** [ndawlab/seqanx#2]
Merry belated Chistmas!
Recently i read your work 'Increased and biased deliberation in social anxiety' that published on Nature this year, and feel inspired with the patent race paradigm.
Would you please share the script that your team run the paradigm with us? I will be preeeeetty appriciate that!

Have a nice day and wish you have a joyful coming new year!

**Comment by szorowi1** [comment]
Hi @nekotalabana, merry Christmas and happy new year!

I believe you're looking for this Github repo: https://github.com/ndawlab/patentrace. This repo is for a different project. Definitely feel free to open an issue there, or reach out to @nathanieldaw directly.
